### ISSUE TITLE
PHP-OCI 8 x86, ARM 도커 이미지 Readme.md 오류

### ISSUE THREAD

**Issue by TopazKang** [2022-DB-502-Group2-Project/Develop-Test-Env#1]
## Issue
***
- 작성된 Readme.md에 `docker run` 명령어중 `-n`이 컨테이너 이름을 말하고 싶은거 같으나, `--name`이 올바른 표기같습니다. 정정해주실수 있으신가요?

**Comment by J-hoplin1** [comment]
고쳤습니당
